#!/usr/bin/env python3
"""Regenerate SKILL-MATRIX.md from the skill files themselves.

The matrix is derived data, so it is generated rather than hand-maintained: a hand-edited
table drifts the moment any skill changes (this repository shipped with 56 of 57 line
counts off by one). Run `python3 scripts/gen_matrix.py` after editing skills, or
`--check` to fail when the committed matrix no longer matches the library.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MATRIX = ROOT / "SKILL-MATRIX.md"
CATEGORY_ORDER = [
    "core", "ai", "coding", "quality", "architecture",
    "devops", "git", "security", "performance", "documentation",
]
CATEGORY_TITLES = {
    "core": "Core analysis", "ai": "AI and reasoning", "coding": "Coding",
    "quality": "Quality", "architecture": "Architecture", "devops": "DevOps",
    "git": "Git", "security": "Security", "performance": "Performance",
    "documentation": "Documentation",
}
PRIORITY_LABEL = {
    "P0": "**P0** (critical)",
    "P1": "**P1** (high)",
    "P2": "**P2** (normal)",
    "P3": "**P3** (standard)",
}
FRONT_RE = re.compile(r"^---\n(.*?)\n---\n", re.S)


def scalar(front: str, key: str) -> str:
    match = re.search(rf"^{re.escape(key)}:[ \t]*(.*)$", front, re.M)
    return match.group(1).strip() if match else ""


def list_field(value: str) -> list[str]:
    inner = value.strip()
    if inner.startswith("[") and inner.endswith("]"):
        inner = inner[1:-1]
    return [item.strip() for item in inner.split(",") if item.strip()]


def load_skills() -> list[dict[str, object]]:
    skills: list[dict[str, object]] = []
    for path in sorted(ROOT.glob("*/*/SKILL.md")):
        text = path.read_text(encoding="utf-8-sig")
        front_match = FRONT_RE.match(text)
        if not front_match:
            raise SystemExit(f"{path}: missing YAML frontmatter")
        front = front_match.group(1)
        name = scalar(front, "name") or path.parent.name
        deps = list_field(scalar(front, "dependencies"))
        skills.append({
            "name": name,
            "category": path.parent.parent.name,
            "priority": scalar(front, "priority") or "P3",
            "dependencies": deps,
            "conflicts": list_field(scalar(front, "conflicts")),
            "lines": len(text.splitlines()),
            "relpath": path.relative_to(ROOT).as_posix(),
        })
    if not skills:
        raise SystemExit("no SKILL.md files found")
    return skills


def render(skills: list[dict[str, object]]) -> str:
    total = sum(int(s["lines"]) for s in skills)
    categories = [c for c in CATEGORY_ORDER if any(s["category"] == c for s in skills)]
    categories += sorted({str(s["category"]) for s in skills} - set(categories))

    out: list[str] = []
    out.append("# 📊 Skill Matrix\n")
    out.append(
        f"## Complete Skill Reference ({len(skills)} Skills · {len(categories)} Categories)\n"
    )
    out.append(
        "Generated by `scripts/gen_matrix.py`; the validator fails if this table drifts from "
        "the skill files.\n"
    )
    out.append("| Skill | Category | Priority | Dependencies | Lines |")
    out.append("|-------|----------|----------|--------------|------:|")
    for category in categories:
        for skill in sorted(
            (s for s in skills if s["category"] == category), key=lambda s: str(s["name"])
        ):
            deps = ", ".join(skill["dependencies"]) if skill["dependencies"] else "-"
            out.append(
                f"| {skill['name']} | {category} | {skill['priority']} | {deps} | {skill['lines']} |"
            )
    out.append("")
    out.append("## Priority Summary\n")
    out.append("| Priority | Skills | Count |")
    out.append("|----------|--------|------:|")
    for priority in ("P0", "P1", "P2", "P3"):
        names = sorted(str(s["name"]) for s in skills if s["priority"] == priority)
        out.append(
            f"| {PRIORITY_LABEL[priority]} | {', '.join(names) if names else '-'} | {len(names)} |"
        )
    out.append("")
    out.append("## Category Summary\n")
    out.append("| Category | Skills | Label |")
    out.append("|----------|-------:|-------|")
    for category in categories:
        count = sum(1 for s in skills if s["category"] == category)
        out.append(f"| {category} | {count} | {CATEGORY_TITLES.get(category, category)} |")
    out.append("")
    out.append(
        f"**Total: {len(skills)} Skills · {total:,} lines** "
        f"(counted with `splitlines()` on every `SKILL.md`, frontmatter included)\n"
    )
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if SKILL-MATRIX.md is stale")
    args = parser.parse_args()
    expected = render(load_skills())
    if args.check:
        current = MATRIX.read_text(encoding="utf-8") if MATRIX.exists() else ""
        if current.rstrip("\n") != expected.rstrip("\n"):
            print("ERROR: SKILL-MATRIX.md is stale; run: python3 scripts/gen_matrix.py", file=sys.stderr)
            return 1
        print("PASS: SKILL-MATRIX.md matches the skill files")
        return 0
    MATRIX.write_text(expected, encoding="utf-8")
    print(f"Wrote {MATRIX.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
